# Generated by Django 2.2.6 on 2019-10-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('row_id', models.UUIDField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('id', models.UUIDField(auto_created=True, editable=False)),
                ('update_id', models.UUIDField(editable=False, unique=True)),
                ('writetime', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
