# Generated by Django 2.2.6 on 2019-10-30 19:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0002_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='mission',
            name='row_id',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='update_id',
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
